spring.application.name=jpatut



spring.datasource.url=jdbc:mysql://localhost:3306/myhiber
spring.datasource.username=root
spring.datasource.password=root1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
#spring.sql.init.data-locations=classpath:data.sql

#logging.level.org.springframework.security=debug


#for cache
spring.cache.type=simple

#actuator
# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

# Optional: Change the base path
management.endpoints.web.base-path=/actuator

#show actuator 
springdoc.show-actuator=true
